Repository tc39/ecma402, pull requests merged in 2021-02, with the labels that each got.

#429 Normative: Do not allow duplicate variants within the `tlang` component of a `transformed_extensions`
  spec/locales-currencies-tz.html
Labels: has consensus, has consensus (TG1), has tests

#500 Normative: Use OrdinaryHasInstance in normative optional steps
  spec/datetimeformat.html
  spec/numberformat.html
Labels: has consensus, has consensus (TG1), needs tests

#532 Normative: Adding Intl.DateTimeFormat formatRange/formatRangeToParts specification
  spec/datetimeformat.html
Labels: has consensus, has consensus (TG1), has tests, stage 4

#538 spec: GetOption reform for ECMA 2021
  spec/displaynames.html
  spec/listformat.html
Labels: c: spec

#539 Editorial: Fix spec typos and GH Workflow
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/require-allow-edits.yml
  spec/annexes.html
  spec/collator.html
  spec/datetimeformat.html
  spec/locales-currencies-tz.html
  spec/numberformat.html
  spec/pluralrules.html
  spec/relativetimeformat.html
Labels: Editorial
