Repository tc39/ecma402, pull requests merged in 2021-01, with the labels that each got.

#456 Normative: Adding Intl.ListFormat specification.
  spec/annexes.html
  spec/conventions.html
  spec/index.html
  spec/listformat.html
  spec/overview.html
Labels: stage 4

#457 Normative: Adding Intl.DateTimeFormat dateStyle/timeStyle specification.
  spec/datetimeformat.html
Labels: stage 4

#459 Normative: Allow Collator to get collation from option
  spec/collator.html
Labels: Small, has consensus, has consensus (TG1), has tests

#471 Normative: handle awkward rounding behavior
  spec/annexes.html
  spec/numberformat.html
Labels: has consensus, has consensus (TG1)

#347 Normative: Add fractionalSecondDigits option
  spec/datetimeformat.html
Labels: Small, c: datetime, enhancement, has consensus, has consensus (TG1), s: in progress

#346 Normative: Add dayPeriod option
  spec/datetimeformat.html
Labels: Small, c: datetime, enhancement, has consensus, needs tests, s: in progress

#502 Normative: Adding Intl.DisplayNames specification.
  spec/annexes.html
  spec/conventions.html
  spec/displaynames.html
  spec/index.html
  spec/overview.html
Labels: stage 4
