Repository tc39/ecma402, pull requests merged in 2023-01, with the labels that each got.

#742 Editorial: Tweak ResolveLocale for clarity
  spec/negotiation.html
Labels: enhancement, editorial, spec-text

#724 Normative: Canonicalise "GMT" to "UTC"
  spec/locales-currencies-tz.html
Labels: has consensus, normative

#714 Normative: Add new numbering systems "kawi" and "nagm"
  spec/numberformat.html
Labels: has consensus, normative

#746 Meta: Cleanup CONTRIBUTING.md
  CONTRIBUTING.md
Labels: meta

#745 Meta: Fix issue templates
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: meta
