Repository tc39/ecma402, pull requests merged in 2024-02, with the labels that each got.

#833 Normative: Allow locale based ignorePunctuation default
  spec/annexes.html
  spec/collator.html
Labels: has consensus, has consensus (TG1), normative

#851 Editorial: regularized wording for table iteration in datetimeformat
  spec/datetimeformat.html
Labels: editorial

#848 Editorial: Remove unnecessary lowercase conversion of key
  spec/negotiation.html
Labels: editorial

#854 Meta: publish biblio in github actions
  .github/workflows/publish-biblio.yml
  biblio/README.md
  biblio/package.json
  scripts/publish-biblio.sh
Labels: meta, needs review

#868 Editorial: Document that DefaultLocale() returns must not include a "-u-" extension
  spec/locales-currencies-tz.html
Labels: editorial

#824 Editorial: Best available locale documentation
  spec/negotiation.html
Labels: editorial, needs review
