Repository tc39/ecma402, pull requests merged in 2024-08, with the labels that each got.

#877 Normative: specify time zone ID requirements to reduce divergence between engines
  spec/locales-currencies-tz.html
Labels: needs tests, has consensus (TG1), normative, needs review

#831 Meta: Update style guide to discuss preferred orderings of elements
  docs/style-guide.md
Labels: meta

#907 Editorial: replaced &ge; &infin; &laquo; &ldquo; &le; &mdash; &ne; &r…
  spec/collator.html
  spec/colophon.html
  spec/conventions.html
  spec/datetimeformat.html
  spec/displaynames.html
  spec/listformat.html
  spec/locale-sensitive-functions.html
  spec/locale.html
  spec/negotiation.html
  spec/normative-references.html
  spec/numberformat.html
  spec/pluralrules.html
  spec/relativetimeformat.html
  spec/segmenter.html
Labels: editorial
